name: flutter_api_model
description: High-level modeling of network requests, which manages input parameters and output parameters, following the "In-Out" naming convention.APIModel doesn't handle network requests directly; instead, it excels at network layer abstraction.
version: 2.0.5
homepage: https://github.com/Meterwhite/flutter_api_model
documentation: https://github.com/Meterwhite/flutter_api_model

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: any
