name: flutter_api_model
description: Modeling of network requests,  which manages input parameters and output parameters, which follows the "In-Out" naming convention.
version: 2.0.3
homepage: https://github.com/Meterwhite/flutter_api_model
documentation: https://github.com/Meterwhite/flutter_api_model

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: any
